// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAlApUQimz4lsIxwdVdnIi08WIPyFAXSkw',
    appId: '1:604952550983:web:4eebdbeb1818730aaa9b62',
    messagingSenderId: '604952550983',
    projectId: 'routine-3fd98',
    authDomain: 'routine-3fd98.firebaseapp.com',
    storageBucket: 'routine-3fd98.firebasestorage.app',
    measurementId: 'G-3P19RNH33R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAa6PrLXQCSLpgeDICbT6Gap3La9qsaPT4',
    appId: '1:604952550983:android:10d179d07d411ce4aa9b62',
    messagingSenderId: '604952550983',
    projectId: 'routine-3fd98',
    storageBucket: 'routine-3fd98.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCU4Ri8MWI1dp1dBdiypJKYMuHDPF2BskM',
    appId: '1:604952550983:ios:a7cfd81694ad0b93aa9b62',
    messagingSenderId: '604952550983',
    projectId: 'routine-3fd98',
    storageBucket: 'routine-3fd98.firebasestorage.app',
    iosBundleId: 'com.example.routine',
  );
}
