/// Flutter icons RoutineFont
/// Copyright (C) 2024 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  RoutineFont
///      fonts:
///       - asset: fonts/RoutineFont.ttf
///
/// 
///
library;
import 'package:flutter/widgets.dart';

class RoutineFont {
  RoutineFont._();

  static const _kFontFam = 'RoutineFont';
  static const String? _kFontPkg = null;

  static const IconData group_35 = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData done_all = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData close = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData check = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sprint = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData flag = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData add = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData home = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData experiment = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData exercise = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData done_outline = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
