const dailyExercises = [
  {
    'name': 'Pushups',
    'type': 'count',
    'counter': 0,
    'goal': 50,
    'increments': [10, 15],
  },
  {
    'name': 'Pullups',
    'type': 'count',
    'counter': 0,
    'goal': 25,
    'increments': [5, 10],
  },
  {
    'name': 'Squats',
    'type': 'count',
    'counter': 0,
    'goal': 50,
    'increments': [10, 20],
  },
  {
    'name': 'Plank',
    'type': 'time',
    'counter': 0,
    'goal': 2,
  },
  {
    'name': 'Situps',
    'type': 'count',
    'counter': 0,
    'goal': 75,
    'increments': [10, 20],
  },
  {
    'name': 'Leg Raises',
    'type': 'count',
    'counter': 0,
    'goal': 20,
    'increments': [10, 20],
  },
  {
    'name': 'Russian Twists',
    'type': 'count',
    'counter': 0,
    'goal': 20,
    'increments': [10, 15],
  },
  {
    'name': 'Mountain Climbers',
    'type': 'count',
    'counter': 0,
    'goal': 100,
    'increments': [20, 25],
  },
];
